name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Build Executable using PyInstaller Action
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'activity_logger.py'
        requirements: 'requirements.txt'
        options: '--onefile, --windowed, --add-data "assets;assets", --icon "assets/activity_logger.ico"'

    - name: 3. Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActivityLogger-Windows-App
        path: dist/windows/activity_logger.exe
