name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Run PyInstaller
      # --- EKHANE PORIBORTON KORA HOYECHE ---
      run: |
        python -m pyinstaller --onefile --windowed --add-data "assets;assets" --icon="assets/activity_logger.ico" activity_logger.py

    - name: 5. Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        # --- EKHANEO PORIBORTON KORA HOYECHE ---
        name: ActivityLogger-Windows-App
        path: dist/activity_logger.exe
