name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Build and Upload Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'activity_logger.py'
        requirements: 'requirements.txt'
        options: '--onefile, --windowed'
        # --- EKHANE PORIBORTON KORA HOYECHE ---
        upload_exe_with_name: 'ActivityLogger-Windows-App'
