name: Build Windows Installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Install Dependencies and Run PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        echo "--- PyInstaller Build Starting ---"
        python -m PyInstaller --onefile --windowed --add-data "assets;assets" --icon="assets/activity_logger.ico" --distpath dist/windows activity_logger.py

    - name: 4. Set up Inno Setup
      run: |
        choco install innosetup --version=6.2.2 -y
      shell: pwsh

    - name: 5. Add Inno Setup to PATH
      run: echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: 6. Compile the Installer
      run: iscc "installer_script.iss"
      shell: cmd

    - name: 7. Upload Installer as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActivityLogger-Installer
        path: Output/ActivityLogger-Setup.exe
