name: Build Windows Installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Run PyInstaller
      run: |
        python -m pyinstaller --onefile --windowed --add-data "assets;assets" --icon="assets/activity_logger.ico" --distpath dist/windows activity_logger.py

    - name: 5. Compile the Installer with Inno Setup
      # --- EKHANE PORIBORTON KORA HOYECHE ---
      # Notun Inno Setup Action bebohar kora hocche
      uses: crazy-max/ghaction-inno-setup@v3
      with:
        script: installer_script.iss

    - name: 6. Upload Installer as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActivityLogger-Installer
        path: Output/ActivityLogger-Setup.exe
