name: Build Windows Installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Run PyInstaller
      run: |
        python -m pyinstaller --onefile --windowed --add-data "assets;assets" --icon="assets/activity_logger.ico" --distpath dist/windows activity_logger.py

    - name: 5. Download and Install Inno Setup
      # --- EKHANE PORIBORTON KORA HOYECHE ---
      # Notun, shorashori Inno Setup download kora hocche
      run: |
        choco install innosetup --version=6.2.2 -y
      shell: pwsh

    - name: 6. Add Inno Setup to PATH
      run: echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: 7. Compile the Installer
      run: iscc "installer_script.iss"
      shell: cmd

    - name: 8. Upload Installer as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActivityLogger-Installer
        path: Output/ActivityLogger-Setup.exe
