```yaml
name: Buildozer Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5:i386 libstdc++6:i386 libz1:i386
        pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install cython==0.29.34

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
```
